## configuration parameters for *p(roton)p(roton)Billiard*

# web cam parameters
camWidth:  1000
camHeight: 800
camFPS:    30
camExposure: null

# properties of trackable objects
objRmin:  15       # minimum radius in pixels
objRmax: 100       # maximum radius in pixels
obj_col1 : [[22, 0, 58],[51, 255, 210]]  # hsv range for green object
obj_col2: [[0, 90, 60], [25, 250, 255]]  # hsv range for red object

# collision detection
fRcollision: 1.9   # distance for detecting collion
fTarget:     0.11  # target region around centre of image

# processing
maxVideoWidth: 1024     # maximum widht of video frames for processing

# images in subrirectory images/ for background and intro
bkgImage: 'RhoZ_black.png'
introImage: 'ppBilliard_intro.png'

# running options 
playIntro: true  # show trailer if true

# video files
defaultVideoFPS: 15     # frame rate for replay of video files 

