## configuration parameters for *p(roton)p(roton)Billiard*

# web cam parameters (acutal values depend on camera model)
camWidth:  1280       # desired picture width
camHeight:  720       # desired picture height
camFPS:      30       # frame rate
camExposure: null     # exposure time in ms
camSaturation: null   # color saturation (depends on camera model)

# properties of trackable objects
objRmin:  15       # minimum radius in pixels
objRmax: 100       # maximum radius in pixels
obj_col1 : [[22, 0, 58],[51, 255, 210]]  # hsv color range for green object
obj_col2: [[0, 90, 60], [25, 250, 255]]  # hsv color range for red object

# collision detection
fRcollision: 1.9   # distance for detecting collion
fTarget:     0.11  # target region around centre of image

# processing
maxVideoWidth: 1024     # maximum widht of video frames for processing

# images for intro and background (in subrirectory images/)
introImage: 'ppBilliard_intro.png'
bkgImage: 'RhoZ_black.png'

# running options 
playIntro: true  # show trailer if true

# video files
defaultVideoFPS: 20     # frame rate for replay of video files 

