## configuration parameters for *p(roton)p(roton)Billiard*
#  -------------------------------------------------------

# web cam parameters (acutal values to be used depend on camera model)
                      # null means take system defaults
camWidth:  1280       # desired picture width  (null)
camHeight:  720       # desired picture height (null)
camFPS:      30       # frame rate             (null)
camExposure: null     # exposure time in ms    (null)
camSaturation: null   # color saturation, depends on camera model (null)

# properties of trackable objects
objRmin:  10       # minimum radius in pixels (10)
objRmax: 100       # maximum radius in pixels (100)
#                      settings here are for example video "Flummies.webm"
obj_col1 : [[23, 0, 50],[51, 255, 255]]  # hsv color range for green object
obj_col2: [[0, 50, 50], [22, 255, 255]]  # hsv color range for red object

# collision detection
fRapproach: 5.0    # scaling of object size close approach (5.0)
fRcollision: 1.7   # scaling of object size for collion detection region (1.5)
fTarget:     0.11  # required target region around centre of image (0.11)
fxROI:  0.7        # tracking region x as fraction of i mage width  (1.0)
fyROI:  1.         # tracking region y as fraction of image height (1.0)

# score rankings (score = CMS energy * impact distance)
superScore: 10000 #
highScore: 1000
lowScore: 500

# video processing
maxVideoWidth: 1024     # maximum width of video frames (1024)

# running options 
playIntro: true        # show trailer if true (true)
motionDetection: true  # differentiate frames to detect ball movements (false)
showMonitoring: true   # show screen with detected objects (false)
verbose: 0             # print detailed information if>0  (0)

# images for intro and background (in subdirectory images/)
introImage: 'ppBilliard_intro.png'
bkgImage: 'RhoZ_black.png'

# video files
defaultVideoFPS: 15     # frame rate for replay of video files  (15)

